import { useEffect, useMemo, useState } from "react";
import "./ProductsPage.css";
const API="http://localhost:5000/api/v1", clean={brand:"",color:"",min:"",max:""};
export default function ProductsPage({language="en",initialCategory="all",dealsOnly=false,onProductClick,onAddToCart,onWishlist}){
 const ar=language==="ar",[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[category,setCategory]=useState(initialCategory),[filters,setFilters]=useState(clean),[loading,setLoading]=useState(true),[colorOpen,setColorOpen]=useState(false);
 const t=ar?{title:dealsOnly?"العروض والخصومات":"تسوق الأجهزة",all:"الكل",filter:"تصفية المنتجات",clear:"مسح الكل",any:"الكل",brand:"العلامة التجارية",color:"اللون",price:"السعر",from:"من",to:"إلى",count:"منتجاً",loading:"جارٍ تحميل المنتجات...",empty:"لم نجد منتجات مطابقة لخياراتك.",add:"أضف للسلة",wish:"المفضلة",store:"متجر أنيس فون"}:{title:dealsOnly?"Deals & Discounts":"Shop Devices",all:"All",filter:"Filter products",clear:"Clear all",any:"Any",brand:"Brand",color:"Color",price:"Price",from:"From",to:"To",count:"products",loading:"Loading products...",empty:"We couldn't find products matching those filters.",add:"Add to cart",wish:"Wishlist",store:"ANIS PHONE STORE"};
 useEffect(()=>setCategory(initialCategory||"all"),[initialCategory]);
 useEffect(()=>{const c=new AbortController();Promise.all([fetch(`${API}/products?limit=100`,{signal:c.signal}),fetch(`${API}/products/categories`,{signal:c.signal})]).then(async([p,k])=>{if(!p.ok||!k.ok)throw Error();return [await p.json(),await k.json()]}).then(([p,k])=>{setProducts(p.data||[]);setCategories(k.data||[])}).catch(e=>{if(e.name!=="AbortError")console.error(e)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[]);
 const options=useMemo(()=>{const brands=new Map(),colors=new Map();products.forEach(p=>{brands.set(p.brand_slug,ar?p.brand_name_ar:p.brand_name_en);[...(p.colors||[]),...(p.variants||[]).flatMap(v=>v.colors||[])].forEach(x=>{const key=String(x.hex_code||x.name_en||x.id).trim().toLowerCase();if(!colors.has(key))colors.set(key,x)})});return{brands:[...brands],colors:[...colors.entries()].map(([key,color])=>({...color,filterKey:key}))}},[products,ar]);
 const shown=useMemo(()=>products.filter(p=>{const price=Number(p.price||0),colors=[...(p.colors||[]),...(p.variants||[]).flatMap(v=>v.colors||[])].map(x=>String(x.hex_code||x.name_en||x.id).trim().toLowerCase());return(category==="all"||p.category_slug===category)&&(!filters.brand||p.brand_slug===filters.brand)&&(!filters.color||colors.includes(filters.color))&&(!filters.min||price>=Number(filters.min))&&(!filters.max||price<=Number(filters.max))&&(!dealsOnly||Number(p.old_price)>price||(p.offers||[]).length)}),[products,category,filters,dealsOnly]);
 const set=(key,value)=>setFilters(x=>({...x,[key]:value})),name=p=>ar?p.name_ar:p.name_en,img=p=>p.images?.find(x=>x.is_primary)?.image_url||p.images?.[0]?.image_url;
 return <section className={`catalog-page ${ar?"rtl":"ltr"}`} dir={ar?"rtl":"ltr"}><div className="catalog-inner"><header className="catalog-header"><div><span>{t.store}</span><h1>{t.title}</h1></div><p>{shown.length} {t.count}</p></header><nav className="category-picker" aria-label="Categories"><button className={category==="all"?"selected":""} onClick={()=>setCategory("all")}>{t.all}</button>{categories.map(x=><button key={x.slug} className={category===x.slug?"selected":""} onClick={()=>setCategory(x.slug)}>{ar?x.name_ar:x.name_en}</button>)}</nav><div className="catalog-filters"><div className="filter-title"><strong>{t.filter}</strong><button onClick={()=>setFilters(clean)}>{t.clear}</button></div><div className="filter-row"><Select label={t.brand} value={filters.brand} items={options.brands} any={t.any} change={v=>set("brand",v)}/><ColorPicker label={t.color} any={t.any} colors={options.colors} isArabic={ar} value={filters.color} open={colorOpen} onToggle={()=>setColorOpen(x=>!x)} onChange={v=>{set("color",v);setColorOpen(false)}}/><label className="price-filter"><span>{t.price}</span><input type="number" min="0" placeholder={t.from} value={filters.min} onChange={e=>set("min",e.target.value)}/><input type="number" min="0" placeholder={t.to} value={filters.max} onChange={e=>set("max",e.target.value)}/></label></div></div>{loading?<div className="catalog-loading">{t.loading}</div>:shown.length?<div className="catalog-grid">{shown.map(p=><article className="catalog-card" key={p.id}><button type="button" className="catalog-image" onClick={()=>onProductClick?.(p.id)}>{img(p)?<img src={img(p)} alt={name(p)}/>:<span>{name(p)}</span>}</button><div className="catalog-card-copy"><p>{ar?p.brand_name_ar:p.brand_name_en}</p><h2>{name(p)}</h2><div className="catalog-card-bottom"><strong>${Number(p.price||0).toLocaleString()}</strong><button aria-label={t.wish} onClick={()=>onWishlist?.(p.id)}>♡</button></div><button className="catalog-add" onClick={()=>onAddToCart?.(p.id)}>{t.add}</button></div></article>)}</div>:<div className="catalog-empty"><p>{t.empty}</p><button onClick={()=>setFilters(clean)}>{t.clear}</button></div>}</div></section>}
function Select({label,value,items,any,change}){return <select value={value} onChange={e=>change(e.target.value)}><option value="">{any} {label}</option>{items.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>}
function ColorPicker({ label, any, colors, isArabic, value, open, onToggle, onChange }) { const selected=colors.find((color)=>color.filterKey===value); return <div className="color-picker"><button type="button" className="color-picker-trigger" onClick={onToggle} aria-haspopup="listbox" aria-expanded={open}>{selected&&<i style={{backgroundColor:selected.hex_code}}/>}<span>{selected?(isArabic?selected.name_ar:selected.name_en):`${any} ${label}`}</span><b>⌄</b></button>{open&&<div className="color-picker-menu" role="listbox"><button type="button" className={!value?"active":""} onClick={()=>onChange("")}><span>{any} {label}</span></button>{colors.map((color)=><button type="button" key={color.filterKey} className={color.filterKey===value?"active":""} onClick={()=>onChange(color.filterKey)}><i style={{backgroundColor:color.hex_code}}/><span>{isArabic?color.name_ar:color.name_en}</span><small>{color.hex_code}</small></button>)}</div>}</div>}
